import { readFile, writeFile, readdir, mkdir, unlink, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const source = path.resolve(process.env.JERBOA_SOURCE || path.join(root, '../jerboa'));
const destination = path.join(root, 'src/pages/docs');
const check = process.argv.includes('--check');
const optional = process.argv.includes('--if-present');
const marker = '<!-- Generated by scripts/sync-docs.mjs. Edit jerboa/docs instead. -->';

try {
  await access(path.join(source, 'docs'));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
  if (!optional || process.env.JERBOA_SOURCE) throw new Error(`Jerboa source missing: ${source}. Set JERBOA_SOURCE to its checkout.`);
  await access(path.join(destination, 'getting-started.md'));
  console.log('Jerboa checkout absent; using the committed documentation snapshot.');
  process.exit(0);
}

const versions = {
  cli: (await readFile(path.join(source, 'VERSION.md'), 'utf8')).trim(),
  kernel: (await readFile(path.join(source, 'kernel/VERSION'), 'utf8')).trim(),
};
const files = (await readdir(path.join(source, 'docs'))).filter(name => name.endsWith('.md')).sort();
const pages = [];
const outputs = new Map();
for (const file of files) {
  if (file === 'index.md') continue; // /docs/ redirects to getting-started; see src/pages/docs/index.astro
  const raw = await readFile(path.join(source, 'docs', file), 'utf8');
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!match) throw new Error(`Missing frontmatter: ${file}`);
  const title = match[1].match(/^title:\s*(.+)$/m)?.[1];
  const order = Number(match[1].match(/^nav_order:\s*(\d+)$/m)?.[1]);
  if (!title || !order) throw new Error(`Missing navigation metadata: ${file}`);
  const slug = file.slice(0, -3);
  const url = slug === 'index' ? '/docs/' : `/docs/${slug}/`;
  pages.push({ title, slug, url, order });
  const body = raw.slice(match[0].length)
    .replace(/## Table of contents\r?\n\{:[^\n]*\}\r?\n\r?\n1\. TOC\r?\n\{:toc\}\r?\n/, '')
    .replace(/\{%\s*link\s+([^\s]+)\s*%\}/g, (_, target) => {
      if (!files.includes(target)) throw new Error(`Unknown documentation link: ${target} in ${file}`);
      return target === 'index.md' ? '/docs/' : `/docs/${target.slice(0, -3)}/`;
    })
    .replace(/\{\{\s*site\.data\.versions\.(cli|kernel)\s*\}\}/g, (_, key) => versions[key])
    .replace(/\{:[^}\n]*\}/g, '')
    .replace(/^\[View on GitHub\]\(https:\/\/github\.com\/AitorConS\/jerboa\)[ \t]*\r?\n/gm, '');
  if (/\{%|\{\{\s*site\./.test(body)) throw new Error(`Unconverted Jekyll syntax: ${file}`);
  outputs.set(path.join(destination, file), `---\nlayout: ../../layouts/Docs.astro\ntitle: ${JSON.stringify(title)}\nsource: ${JSON.stringify(file)}\n---\n${marker}\n${body.trim()}\n`);
}
pages.sort((a, b) => a.order - b.order);
outputs.set(path.join(root, 'src/data/docs.json'), JSON.stringify({ versions, pages }, null, 2) + '\n');
await mkdir(destination, { recursive: true });
const stale = [];
for (const file of await readdir(destination)) {
  const target = path.join(destination, file);
  if (!outputs.has(target) && file.endsWith('.md') && (await readFile(target, 'utf8')).includes(marker)) stale.push(target);
}
let differences = stale.length;
for (const [target, content] of outputs) {
  const previous = await readFile(target, 'utf8').catch(error => {
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (previous === content) continue;
  differences++;
  if (check) console.error(`Out of sync: ${path.relative(root, target)}`);
  else await writeFile(target, content);
}
for (const target of stale) {
  if (check) console.error(`Obsolete: ${path.relative(root, target)}`);
  else await unlink(target);
}
if (check && differences) process.exitCode = 1;
console.log(`${pages.length} documentation pages ${check ? 'checked' : 'synchronized'} (CLI ${versions.cli}, kernel ${versions.kernel}); ${differences} ${check ? 'differences' : 'updates'}.`);
